#include "typescript.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Embedded Sucrase bundle (generated by xxd -i from vendor/sucrase-bundle.js) */
#include "sucrase_bundle.h"

/* String-based JSX runtime prepended to .tsx output. Kept compact to minimize
 * source map line offset (2 lines). */
static const char JSX_RUNTIME[] =
    "const __VOID=new Set([\"area\",\"base\",\"br\",\"col\",\"embed\",\"hr\","
    "\"img\",\"input\",\"link\",\"meta\",\"param\",\"source\",\"track\",\"wbr\"]);\n"
    "function __jsx(t,p,...c){if(typeof t===\"function\")return t({...p,children:c});"
    "let s=\"<\"+t;if(p)for(const[k,v]of Object.entries(p)){"
    "if(v===false||v==null)continue;"
    "if(v===true){s+=\" \"+k;continue;}"
    "s+=\" \"+k+'=\"'+String(v).replace(/&/g,\"&amp;\").replace(/\"/g,\"&quot;\")+'\"';}"
    "if(__VOID.has(t))return s+\" />\";s+=\">\";"
    "for(const x of c){if(x==null||x===false||x===true)continue;"
    "if(Array.isArray(x))for(const i of x){if(i!=null&&i!==false&&i!==true)s+=String(i);}"
    "else s+=String(x);}return s+\"</\"+t+\">\";}"
    "function __jsxFrag(_p,...c){let s=\"\";for(const x of c)"
    "if(x!=null&&x!==false&&x!==true)s+=String(x);return s;}\n";

int sjs_typescript_init(JSContext *ctx, sjs_ts_ctx_t *ts) {
    memset(ts, 0, sizeof(*ts));
    ts->ctx = ctx;
    ts->transform_fn   = JS_UNDEFINED;
    ts->ts_options     = JS_UNDEFINED;
    ts->tsx_options     = JS_UNDEFINED;
    ts->json_stringify = JS_UNDEFINED;

    /* Evaluate the Sucrase IIFE bundle — defines globalThis.sucrase */
    JSValue ret = JS_Eval(ctx,
        (const char *)sucrase_bundle_js, sucrase_bundle_js_len,
        "<sucrase>", JS_EVAL_TYPE_GLOBAL);

    if (JS_IsException(ret)) {
        JSValue exc = JS_GetException(ctx);
        const char *msg = JS_ToCString(ctx, exc);
        fprintf(stderr, "shift-js: sucrase eval error: %s\n", msg ? msg : "?");
        JS_FreeCString(ctx, msg);
        JS_FreeValue(ctx, exc);
        JS_FreeValue(ctx, ret);
        return -1;
    }
    JS_FreeValue(ctx, ret);

    /* Get sucrase.transform from globalThis */
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue sucrase = JS_GetPropertyStr(ctx, global, "sucrase");
    if (JS_IsUndefined(sucrase) || JS_IsException(sucrase)) {
        fprintf(stderr, "shift-js: sucrase global not found after eval\n");
        JS_FreeValue(ctx, sucrase);
        JS_FreeValue(ctx, global);
        return -1;
    }

    ts->transform_fn = JS_GetPropertyStr(ctx, sucrase, "transform");
    JS_FreeValue(ctx, sucrase);

    if (!JS_IsFunction(ctx, ts->transform_fn)) {
        fprintf(stderr, "shift-js: sucrase.transform is not a function\n");
        JS_FreeValue(ctx, ts->transform_fn);
        ts->transform_fn = JS_UNDEFINED;
        JS_FreeValue(ctx, global);
        return -1;
    }

    /* Cache JSON.stringify for source map serialization */
    JSValue json_obj = JS_GetPropertyStr(ctx, global, "JSON");
    ts->json_stringify = JS_GetPropertyStr(ctx, json_obj, "stringify");
    JS_FreeValue(ctx, json_obj);
    JS_FreeValue(ctx, global);

    /* Build options: {transforms: ["typescript"], sourceMapOptions: {...}} */
    ts->ts_options = JS_NewObject(ctx);
    JSValue ts_arr = JS_NewArray(ctx);
    JS_SetPropertyUint32(ctx, ts_arr, 0, JS_NewString(ctx, "typescript"));
    JS_SetPropertyStr(ctx, ts->ts_options, "transforms", ts_arr);
    JSValue ts_smo = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, ts_smo, "compiledFilename",
                      JS_NewString(ctx, "module.ts"));
    JS_SetPropertyStr(ctx, ts->ts_options, "sourceMapOptions", ts_smo);
    JS_SetPropertyStr(ctx, ts->ts_options, "filePath",
                      JS_NewString(ctx, "module.ts"));

    /* Build options: {transforms: ["typescript", "jsx"],
     *                 jsxPragma: "__jsx", jsxFragmentPragma: "__jsxFrag",
     *                 production: true, sourceMapOptions: {...}} */
    ts->tsx_options = JS_NewObject(ctx);
    JSValue tsx_arr = JS_NewArray(ctx);
    JS_SetPropertyUint32(ctx, tsx_arr, 0, JS_NewString(ctx, "typescript"));
    JS_SetPropertyUint32(ctx, tsx_arr, 1, JS_NewString(ctx, "jsx"));
    JS_SetPropertyStr(ctx, ts->tsx_options, "transforms", tsx_arr);
    JS_SetPropertyStr(ctx, ts->tsx_options, "jsxPragma",
                      JS_NewString(ctx, "__jsx"));
    JS_SetPropertyStr(ctx, ts->tsx_options, "jsxFragmentPragma",
                      JS_NewString(ctx, "__jsxFrag"));
    JS_SetPropertyStr(ctx, ts->tsx_options, "production", JS_TRUE);
    JSValue tsx_smo = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, tsx_smo, "compiledFilename",
                      JS_NewString(ctx, "module.tsx"));
    JS_SetPropertyStr(ctx, ts->tsx_options, "sourceMapOptions", tsx_smo);
    JS_SetPropertyStr(ctx, ts->tsx_options, "filePath",
                      JS_NewString(ctx, "module.tsx"));

    /* Set up per-extension bindings */
    ts->ts_binding.ts_ctx  = ts;
    ts->ts_binding.options = &ts->ts_options;
    ts->ts_binding.is_tsx  = 0;
    ts->ts_binding.last_source_map = NULL;
    ts->ts_binding.last_source_map_len = 0;

    ts->tsx_binding.ts_ctx  = ts;
    ts->tsx_binding.options = &ts->tsx_options;
    ts->tsx_binding.is_tsx  = 1;
    ts->tsx_binding.last_source_map = NULL;
    ts->tsx_binding.last_source_map_len = 0;

    ts->initialized = 1;
    return 0;
}

char *sjs_typescript_transform(const char *source, size_t len,
                                size_t *out_len, void *user_data) {
    sjs_ts_binding_t *binding = user_data;
    if (!binding || !binding->ts_ctx || !binding->ts_ctx->initialized)
        return NULL;

    sjs_ts_ctx_t *ts = binding->ts_ctx;
    JSContext *ctx = ts->ctx;
    JSValue options = *binding->options;

    /* Clear previous source map */
    free(binding->last_source_map);
    binding->last_source_map = NULL;
    binding->last_source_map_len = 0;

    /* Update filePath dynamically for accurate source maps */
    if (ts->current_module_path) {
        JS_SetPropertyStr(ctx, options, "filePath",
                          JS_NewString(ctx, ts->current_module_path));
        JSValue smo = JS_GetPropertyStr(ctx, options, "sourceMapOptions");
        if (!JS_IsUndefined(smo)) {
            JS_SetPropertyStr(ctx, smo, "compiledFilename",
                              JS_NewString(ctx, ts->current_module_path));
            JS_FreeValue(ctx, smo);
        }
    }

    JSValue source_str = JS_NewStringLen(ctx, source, len);
    if (JS_IsException(source_str)) return NULL;

    JSValue args[2] = { source_str, options };
    JSValue result = JS_Call(ctx, ts->transform_fn, JS_UNDEFINED, 2, args);
    JS_FreeValue(ctx, source_str);

    if (JS_IsException(result)) {
        JSValue exc = JS_GetException(ctx);
        const char *msg = JS_ToCString(ctx, exc);
        fprintf(stderr, "shift-js: sucrase transform error: %s\n",
                msg ? msg : "?");
        JS_FreeCString(ctx, msg);
        JS_FreeValue(ctx, exc);
        JS_FreeValue(ctx, result);
        return NULL;
    }

    /* Extract .code */
    JSValue code_val = JS_GetPropertyStr(ctx, result, "code");

    /* Extract .sourceMap if present */
    JSValue sm_val = JS_GetPropertyStr(ctx, result, "sourceMap");
    if (!JS_IsUndefined(sm_val) && !JS_IsNull(sm_val)) {
        JSValue sm_json = JS_Call(ctx, ts->json_stringify, JS_UNDEFINED,
                                  1, &sm_val);
        if (JS_IsString(sm_json)) {
            size_t sm_len;
            const char *sm_str = JS_ToCStringLen(ctx, &sm_len, sm_json);
            if (sm_str) {
                binding->last_source_map = malloc(sm_len + 1);
                if (binding->last_source_map) {
                    memcpy(binding->last_source_map, sm_str, sm_len);
                    binding->last_source_map[sm_len] = '\0';
                    binding->last_source_map_len = sm_len;
                }
                JS_FreeCString(ctx, sm_str);
            }
        }
        JS_FreeValue(ctx, sm_json);
    }
    JS_FreeValue(ctx, sm_val);
    JS_FreeValue(ctx, result);

    if (JS_IsUndefined(code_val) || JS_IsException(code_val)) {
        JS_FreeValue(ctx, code_val);
        return NULL;
    }

    size_t js_len;
    const char *js = JS_ToCStringLen(ctx, &js_len, code_val);
    JS_FreeValue(ctx, code_val);
    if (!js) return NULL;

    /* Build output: prepend JSX runtime for .tsx files */
    size_t runtime_len = binding->is_tsx ? (sizeof(JSX_RUNTIME) - 1) : 0;
    char *out = malloc(runtime_len + js_len + 1);
    if (!out) {
        JS_FreeCString(ctx, js);
        return NULL;
    }
    if (runtime_len > 0)
        memcpy(out, JSX_RUNTIME, runtime_len);
    memcpy(out + runtime_len, js, js_len);
    out[runtime_len + js_len] = '\0';
    JS_FreeCString(ctx, js);

    *out_len = runtime_len + js_len;
    return out;
}

void sjs_typescript_free(sjs_ts_ctx_t *ts) {
    if (!ts || !ts->initialized) return;
    JS_FreeValue(ts->ctx, ts->transform_fn);
    JS_FreeValue(ts->ctx, ts->ts_options);
    JS_FreeValue(ts->ctx, ts->tsx_options);
    JS_FreeValue(ts->ctx, ts->json_stringify);
    free(ts->ts_binding.last_source_map);
    free(ts->tsx_binding.last_source_map);
    ts->transform_fn   = JS_UNDEFINED;
    ts->ts_options     = JS_UNDEFINED;
    ts->tsx_options     = JS_UNDEFINED;
    ts->json_stringify = JS_UNDEFINED;
    ts->initialized    = 0;
}
